method: onet
data:
  path: data/manh1kr_output #change maybe /home/alberto/Documents/occupancy_networks/out/img/onet/generation_200000_cunny-blender-r-s
  img_folder: img_choy2016
  img_size: 224 
  points_subsample: 2048 #changed from 2048
model:
  encoder_latent: null #changed null / simple
  decoder: cbatchnorm #changed cbatchnorm
  encoder: resnet18
  c_dim: 256 #change 256
  z_dim: 0
training:
  out_dir: out/2_PFTA/onet #Change to out/img_previous/onet--> / or out/img/onet [ OUTPUT OF EVALUATION]
  batch_size: 32 #changed
  model_selection_metric: iou #change iou
  model_selection_mode: maximize #changed maximize
  visualize_every: 2000 #changed 20000
  validate_every: 2000 #changed 20000
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
  model_file: model_best.pt #changed model_best
generation:
  batch_size: 10000 #changed 100000
  refine: false
  n_x: 128
  n_z: 1
  resolution_0: 32 
  upsampling_steps: 2

